#!/bin/bash
#SBATCH -N 4
#SBATCH -C gpu
#SBATCH -G 16
#SBATCH -q premium
#SBATCH -J transm_L
#SBATCH -A m3766
#SBATCH -t 40:00:00

# OpenMP settings:
export OMP_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread

#run the application: 
# applications may perform better with --gpu-bind=none instead of --gpu-bind=single:1
srun -n 16 -c 32 --cpu_bind=cores -G 16 ./main3d.gnu.TPROF.MTMPI.CUDA.ex input
